# Generated by Django 3.0.5 on 2020-05-02 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, verbose_name='Kullanıcı Adı')),
                ('hastag', models.CharField(max_length=100, verbose_name='Hastag')),
                ('tweet', models.CharField(max_length=200, verbose_name='Tweet')),
                ('userAvatar', models.CharField(max_length=500, verbose_name='Avatar')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullancı')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('dosyaNumarası', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Dosya Numarası')),
                ('hastag', models.CharField(max_length=100, verbose_name='Hastag')),
                ('oran', models.CharField(max_length=100, verbose_name='Tweet Özgünlük Oranı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kelime Haritası')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='CSV Dosya Seçiniz')),
                ('tweetCount', models.IntegerField(default=0, verbose_name='Toplam Tweet Sayısı')),
                ('pozitifTweet', models.IntegerField(default=0, verbose_name='Pozitif Tweet Sayısı')),
                ('negatifTweet', models.IntegerField(default=0, verbose_name='Negatif Tweet Sayısı')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullancı')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('mesaj', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('alıcı', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Gönderilen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Kullancı')),
            ],
        ),
    ]
