# Generated by Django 3.0.6 on 2020-05-29 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='tweetharitasi',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='oran',
            new_name='tweetozgunluk',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tweetCount',
            new_name='tweetsayisi',
        ),
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='projeadi',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Proje Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tweetdosyasi',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tweet CSV Dosya Seçiniz'),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetgundagilimi',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Tweet Gün Dağılımı'),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetkaynak',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tweetlerin Atıldığı Kaynak'),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetlokasyondagilim',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tweet Lokasyon Dağılımı'),
        ),
    ]
