# Generated by Django 3.0.6 on 2020-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200529_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweetfrekans',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kelimeler'),
        ),
    ]
