# Generated by Django 3.0.6 on 2020-06-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_post_tweetfrekans'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweet',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Retweet CSV Dosya Seçiniz'),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetfrekanscsv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Kelime Frekans Csv Dosyası'),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetgundagilimicsv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tweet Gün Dağılımı Csv Dosyası '),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetlokasyondagilimcsv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tweet Lokasyon Dağılımı Csv Dosyası'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mesaj',
            field=models.TextField(max_length=600, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetfrekans',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kelime Frekans Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetgundagilimi',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tweet Gün Dağılımı Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetharitasi',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kelime Haritası Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetkaynak',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tweetlerin Atıldığı Kaynak Csv Kaynak'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetlokasyondagilim',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tweet Lokasyon Dağılımı Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetozgunluk',
            field=models.CharField(max_length=100, null=True, verbose_name='Tweet Özgünlük Oranı'),
        ),
    ]
