# Generated by Django 3.0.6 on 2020-06-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0004_auto_20200602_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aad', models.CharField(max_length=100, verbose_name='Analiz Adı')),
                ('Akonu', models.CharField(max_length=100, verbose_name='Analiz Konusu')),
                ('Amesaj', models.TextField(max_length=600, verbose_name='Analiz Hakkında Beklenti')),
                ('Ahastag', models.CharField(max_length=100, verbose_name='Konu Hastag')),
                ('baslangictarihi', models.DateField(verbose_name='Başlangıç Tarih')),
                ('bitistarihi', models.DateField(verbose_name='Bitiş Tarih')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('Auser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzes', to=settings.AUTH_USER_MODEL, verbose_name='Kullancı')),
                ('Zalıci', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Gönderilen')),
            ],
        ),
    ]
