# Generated by Django 3.0.6 on 2020-06-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0005_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='Zalıci',
            new_name='Aalıci',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullancı '),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='userName',
            field=models.CharField(max_length=100, verbose_name='Kullanıcı Adı '),
        ),
    ]
