# Generated by Django 3.0.6 on 2020-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20200606_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweetkaynakcsv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tweetlerin Atıldığı Kaynak Csv Kaynak'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetkaynak',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tweetlerin Atıldığı Kaynak Resim'),
        ),
    ]
