# Generated by Django 3.0.6 on 2020-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_auto_20200606_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='durum',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tweet'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='hastag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hastag'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tweet'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='userAvatar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='userName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kullanıcı Adı '),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
